path:
  data_dir: "./data"
  img_dir: "./data/images_raw"
  output_dir: "./data/output"
  json_dir: "./data/json"

yolo:
  model_path: "models/yolo11x.pt"
  return_vis: true

ocr:
  return_vis: true
  langs:
    - "ko"
    - "en"

captioning:
  model: "llava-hf/llava-1.5-7b-hf"
  prompt: "Factually describe the objects, materials, and actions that are clearly visible in the image. Use precise and natural sentences."

LLM:
  model: "google/gemma-3-12b-it"
  prompt_template: >
    Caption: "{caption}"
    Question: Is this caption realistic and detailed enough to generate accurate image-based hashtags, without any exaggeration or imagination?
    **Answer with only one word: Suitable or Unsuitable.
  suitable_keywords: ["suitable"]
  unsuitable_keywords: ["unsuitable"]
  skip_if_judged: true
  max_new_tokens: 30
  response_field_name: "LLM_response"
  temperature: 0.7
  top_p: 0.9

caption_filtering:
  food_keywords:
    - bowl
    - pizza
    - ramen
    - cake
    - dish
    - plate
    - steak
    - burger
    - fries
    - sushi
    - spoon
    - fork

  emotional_keywords:
    - window
    - sunset
    - book
    - flower
    - cat
    - dog
    - rain
    - candle
    - face
    - smile
    - couple
    - person
    - lamp
    - street
    - bed